# Generated by Django 3.2.2 on 2021-06-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_dogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dogs',
        ),
    ]
